"""Generate a Pine Script indicator with embedded buy/sell markers for one analysis run.

Users paste this into TradingView as a Pine v5 indicator to see signals on their charts.
This works for every TradingView plan tier (Essential included) because it does not rely
on external webhook alerts — it's a static overlay driven by embedded arrays.
"""
from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

from sqlalchemy import select

from app.config import get_settings
from app.db import session_scope
from app.models import AnalysisRun, Signal

log = logging.getLogger(__name__)


PINE_TEMPLATE = """//@version=5
indicator("Investment Agent Signals — Run #{run_id}", overlay=true)

// Generated by My Investment Agent on {generated_at}
// Horizon: {horizon}   |   Tickers: {ticker_list}

// --- Signal table ---
// ticker, action, buy_low, buy_high, sell_low, sell_high, stop_loss, target_pct
// Arrays below are parallel lists.
var string[]  t_tick       = array.from({tick_arr})
var string[]  t_action     = array.from({action_arr})
var float[]   t_buy_low    = array.from({buy_low_arr})
var float[]   t_buy_high   = array.from({buy_high_arr})
var float[]   t_sell_low   = array.from({sell_low_arr})
var float[]   t_sell_high  = array.from({sell_high_arr})
var float[]   t_stop       = array.from({stop_arr})
var float[]   t_target     = array.from({target_arr})
var float[]   t_conf       = array.from({conf_arr})

current_ticker = syminfo.ticker
idx = -1
for i = 0 to array.size(t_tick) - 1
    if array.get(t_tick, i) == current_ticker
        idx := i
        break

if idx >= 0
    act = array.get(t_action, idx)
    bl  = array.get(t_buy_low, idx)
    bh  = array.get(t_buy_high, idx)
    sl  = array.get(t_sell_low, idx)
    sh  = array.get(t_sell_high, idx)
    stp = array.get(t_stop, idx)
    tpc = array.get(t_target, idx)
    cf  = array.get(t_conf, idx)

    bg = act == "BUY" ? color.new(color.green, 85) : act == "SELL" ? color.new(color.red, 85) : color.new(color.gray, 90)
    bgcolor(bg)

    // Entry band
    if not na(bl) and not na(bh)
        hline(bl, "Entry Low",  color=color.new(color.green, 20), linestyle=hline.style_dashed)
        hline(bh, "Entry High", color=color.new(color.green, 20), linestyle=hline.style_dashed)
    // Exit band
    if not na(sl) and not na(sh)
        hline(sl, "Exit Low",   color=color.new(color.orange, 20), linestyle=hline.style_dotted)
        hline(sh, "Exit High",  color=color.new(color.orange, 20), linestyle=hline.style_dotted)
    // Stop
    if not na(stp)
        hline(stp, "Stop",       color=color.new(color.red, 10), linestyle=hline.style_solid)

    // Label
    if barstate.islast
        txt = "AGENT: " + act + "  conf=" + str.tostring(cf, "#.##") + "  size=" + str.tostring(tpc, "#.#") + "%"
        label.new(bar_index, close, txt,
                  style=act == "BUY" ? label.style_label_up : act == "SELL" ? label.style_label_down : label.style_label_left,
                  color=act == "BUY" ? color.green : act == "SELL" ? color.red : color.gray,
                  textcolor=color.white, size=size.normal)
"""


def _fmt_arr(vals: list[Any], is_str: bool = False) -> str:
    if not vals:
        return '""' if is_str else "na"
    if is_str:
        return ", ".join([f'"{v}"' for v in vals])
    return ", ".join([(str(v) if v is not None else "na") for v in vals])


async def write_pine_script(run_id: int) -> Path:
    cfg = get_settings()
    async with session_scope() as db:
        run = await db.get(AnalysisRun, run_id)
        if not run:
            raise ValueError(f"Run {run_id} not found")
        stmt = select(Signal).where(Signal.run_id == run_id)
        sigs = (await db.execute(stmt)).scalars().all()
        if not sigs:
            raise ValueError(f"No signals for run {run_id}")
        horizon = sigs[0].time_horizon if sigs else "swing"

        ticker_list = ", ".join([s.ticker for s in sigs])

        rendered = PINE_TEMPLATE.format(
            run_id=run_id,
            generated_at=run.started_at.isoformat(),
            horizon=horizon,
            ticker_list=ticker_list,
            tick_arr=_fmt_arr([s.ticker for s in sigs], is_str=True),
            action_arr=_fmt_arr([s.action for s in sigs], is_str=True),
            buy_low_arr=_fmt_arr([s.buy_low for s in sigs]),
            buy_high_arr=_fmt_arr([s.buy_high for s in sigs]),
            sell_low_arr=_fmt_arr([s.sell_low for s in sigs]),
            sell_high_arr=_fmt_arr([s.sell_high for s in sigs]),
            stop_arr=_fmt_arr([s.stop_loss for s in sigs]),
            target_arr=_fmt_arr([s.target_pct for s in sigs]),
            conf_arr=_fmt_arr([round(s.confidence, 3) for s in sigs]),
        )

    out_dir = cfg.pine_path
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"run_{run_id}.pine"
    path.write_text(rendered, encoding="utf-8")
    log.info("Pine script written: %s", path)
    return path
